# Redis Server Configuration
spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost #127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_test_db
    username: root
    password: rootDB
    driver-class-name:
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect This is selected by default
    hibernate:
      ddl-auto: update
    show-sql: true
